### ISSUE TITLE
Generate Mathematica paclet documentation files from markdown

### ISSUE THREAD

**Issue by taliesinb** [maxitg/SetReplace#485] opened 2020-10-17 13:20 UTC
### The problem

Idea 1: While working with SetReplace functionality in Mathematica, it would be convenient if one could bring up the ordinary Mathematica documentation (e.g. pressing F1) on any given function. This would be nice for reasons that Mathematica's documentation is nice: one can evaluate examples in-line, tables of options are easy to read and can be easily navigated, "See also" makes it easy to jump around between documentation pages, etc.

Idea 2: Similarly, it would be *very* nice if all of our research notes became part of the paclet as well (although I can imagine file size might be a challenge here). That would make it instantaneous to "jump to the start of the art" and start playing around with a given model in Mathematica, turning the paclet itself into a kind of interactive textbook. 

The good news is that this kind of functionality is well supported in Mathematica via paclet documentation, which allow a paclet to contain ordinary Mathematica documentation that works in the ordinary way. How do we build these notebooks, however?

### Possible solution

Markdown is the appropriate format for creating, reviewing, and editing documentation for the reasons we all already know. Hence, if we can have an automated script assemble the correct [docutools notebooks](https://reference.wolfram.com/workbench/index.jsp?topic=/com.wolfram.eclipse.help/html/tasks/documentationpaclets/documentationtools.html) from our existing markdown function documentation then all of this functionality would basically come for free!

As for idea 2, If we think it is not appropriate to bundle research notes as part of the paclet, would could instead create a separate paclet that contains just the research nodes. This is slightly less ideal, since you could have conflicting versions checked out in which the research notes, when run, would not produce the correct output. However there could be automated workarounds for this, such as having a dynamic cell in the documentation notebook that checks at run-time whether the version of the SetReplace paclet is correct.

### Alternative solutions

We could author corresponding Mathematica docutools-based documentation by hand, but this does not seem like a realistic workflow to me.

We could maintain the current status quo of not having deep in-product documentation, but I think this is less than ideal.

### Additional context

This issue relates to https://github.com/maxitg/SetReplace/issues/449, which initially expressed a more ambitious scope that included bidirectional translation between notebooks and markdown. This proposal would require the markdown ⇒ notebook translation.

**Comment by maxitg** [comment] 2020-10-18 03:30
Duplicate of #27.

Note that our current documentation has a drastically different format than the documentation for built-in functions. Our documentation is written as a guide where the Mathematica convention for documentation is to make it brief with lots of examples.

So, even though we might want to use Markdown and the system from #449 to generate these notebooks, we will still have to rewrite existing documentation to be consistent with the expected style.

**Closed by maxitg** 2020-10-18 03:30 UTC
Labels: duplicate, feature, infrastructure
